### ISSUE TITLE
Unable to install on Python 3.3

### ISSUE THREAD

**Issue by jensenbox** [joestump/python-oauth2#147]
```
Downloading/unpacking oauth2 (from -r /home/christian/documents/projects/rh/requirements.txt (line 49))
  Downloading oauth2-1.5.211.tar.gz
  Running setup.py egg_info for package oauth2
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip_build_christian/oauth2/setup.py", line 18
        print "unable to find version in %s" % (VERSIONFILE,)
                                           ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip_build_christian/oauth2/setup.py", line 18

    print "unable to find version in %s" % (VERSIONFILE,)

                                       ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_christian/oauth2
Storing complete log in /home/christian/.pip/pip.log
```

**Comment by jaitaiwan** [comment]
@jensenbox do you mind closing this issue? This repo is dead.

**Comment by joestump** [comment]
See #158. @jaitaiwan is working on PT3K support. Also, praise be to Gaia for this repo has risen! :innocent:
