### ISSUE TITLE
Request.to_url() fails with non-ascii query parameters

### ISSUE THREAD

**Issue by thisfred** [joestump/python-oauth2#154]
>>> kw = {'foo': u'fnørd'}
    >>> r = oauth2.Request('GET', 'http://foo.org', parameters=kw)
    >>> r.to_url()
    Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "/home/eric/trapit/nibbler/.virt/local/lib/python2.7/site-packages/oauth2/__init__.py", line 440, in to_url
        urllib.urlencode(query, True), fragment)
      File "/usr/lib/python2.7/urllib.py", line 1354, in urlencode
        l.append(k + '=' + quote_plus(str(elt)))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 2: ordinal not in range(128)

the bizarre thing is, not even passing in pre-encoded utf-8 values will fix this:

    >>> kw = {'foo': u'ønø'.encode('utf-8')}
    >>> r = oauth2.Request('GET', 'http://foo.org', parameters=kw)
    >>> r.to_url()
    Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "oauth2/__init__.py", line 440, in to_url
        urllib.urlencode(query, True), fragment)
      File "/usr/lib/python2.7/urllib.py", line 1354, in urlencode
        l.append(k + '=' + quote_plus(str(elt)))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 0: ordinal not in range(128)

because Request goes out of its way to decode the query parameters it gets to unicode. 

I have a patch, will send a PR.

**Comment by joestump** [comment]
Fixes related to this have been merged. All should be well with UTF-8 again.
